### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by lmn8** [lmn8/nord-geshi#28]
- [x] [Add CodeColorer support.](https://github.com/lmn8/nord-geshi/issues/22)
- [x] [Improve customisation guide for container selectors.](https://github.com/lmn8/nord-geshi/issues/23)
- [x] [Increase feature completeness to 100%.](https://github.com/lmn8/nord-geshi/issues/24)
- [x] Only apply colors when GeSHi container selector is properly customised.
- [x] [Proofread README guide additions.](https://github.com/lmn8/nord-geshi/commit/49a4c23)
- [x] Add a `.gitattributes` file for line EOF normalisation.
- [x] Bump version, then publish to NPM and Github Packages.
